Feat/siman
ochamodev/compara_precios_scrapers pull request #2
Opened 2024-08-01 18:00 UTC by ochamodev

A preview of the Siman website's scraper

2024-08-02 17:40 UTC, linder3hs requested changes

2024-08-02 17:40 UTC, linder3hs commented on src/siman/siman_scraper.ts
> +    async start() {
creo que acá podrías mejorar la indentación a 2 spaces o 1 tab por ser JS

2024-08-02 17:40 UTC, linder3hs commented on src/siman/siman_scraper.ts
> +                        setTimeout(() => {
acá puede usar algo de `playwright` para hacer que espere 1seg?

2024-08-02 17:40 UTC, linder3hs commented on src/siman/siman_scraper.ts
> +                        if (viewMoreBtn != null) {
en JS no hace falta evaluar el `!= null`
```
 if (viewMoreBtn) {
 }
 ```

2024-08-02 17:40 UTC, linder3hs commented on src/siman/siman_scraper.ts
> +                        if (listPriceValue == null) {
```ts
if (!listPriceValue) {
```

2024-08-02 17:40 UTC, linder3hs commented on src/siman/utils/scraping_utils.ts
> +    if (link === null) {
```ts
if (!link) {

```

2024-08-05 16:27 UTC, erickpac commented on src/siman/siman_scraper.ts
> +                            name: productName ? productName : "",
para evitar hacer un ternario acá podes hacer esto `name: productName ?? ""`

2024-08-06 03:28 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +    async start() {
Ah podrías revisar again, en teoría con los cambios incorporados de @erickpac debería estar mejor ahora jejeje

2024-08-06 04:01 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +                        setTimeout(() => {
Listo lo hice con el waitForSelector :)

2024-08-06 04:01 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +                        if (viewMoreBtn != null) {
Done

2024-08-06 04:01 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +                        if (listPriceValue == null) {
Done

2024-08-06 04:01 UTC, ochamodev commented on src/siman/utils/scraping_utils.ts
> +    if (link === null) {
Done

2024-08-06 04:02 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +                            name: productName ? productName : "",
Buena onda :D 👍

2024-08-08 23:15 UTC, gianfranco03 requested changes

2024-08-08 23:15 UTC, gianfranco03 commented on src/siman/siman_scraper.ts
> +            for (let pageNum = 2; ; pageNum++) {
No debería iniciar en 1?

2024-08-08 23:15 UTC, gianfranco03 commented on src/siman/siman_scraper.ts
> +                    const productModel = await page.evaluate((data) => {
Considero que podemos mover toda esta sección a un nuevo método separado

2024-08-08 23:15 UTC, gianfranco03 commented on src/siman/utils/scraping_utils.ts
> +}
Sino hay algo que sea solo para Siman, podemos mover esta function a `common/utils`

2024-08-09 00:52 UTC, ochamodev commented on src/siman/utils/scraping_utils.ts
> +}
Listo lo moví :)

2024-08-09 00:53 UTC, ochamodev commented on src/siman/siman_scraper.ts
> +                    const productModel = await page.evaluate((data) => {
Movido :)

2024-08-09 14:48 UTC, gianfranco03 approved these changes

2024-08-09 15:16 UTC, erickpac approved these changes

2024-08-09 20:14 UTC, merged