Tiendas Max bot
ochamodev/compara_precios_scrapers pull request #4
Opened 2024-08-05 21:41 UTC by gianfranco03

2024-08-05 23:47 UTC, erickpac commented on src/max/max_scraper.ts
> +      while (true) {
considero que `while (true)` puede ser mentiroso, podemos manejar diferente la condición? como: `while (isListEmpty)` y al final del while `isListEmpty = await this.isProductListEmpty(page)`

2024-08-05 23:49 UTC, erickpac commented
Todo se ve muy bien, solo un comentario pequeño además de: podemos separar en pequeñas partes el método `start()`? dividir las responsabilidades me refiero

2024-08-07 17:39 UTC, linder3hs requested changes

2024-08-07 17:39 UTC, linder3hs commented on src/max/max_scraper.ts
> +    const thereAreNoItemsMessage = await page.evaluate(() => {
creo que podemos simplificarlo a
```ts
const thereAreNoItemsMessage = await page.evaluate(() => {
  return document.querySelector(".message.info.empty");
});
return thereAreNoItemsMessage;
```

2024-08-13 00:26 UTC, erickpac approved these changes

2024-08-13 00:26 UTC, merged